CREATE DCM PROJECT DCM_LEARNING.TEST.NEW_DCM_PROJECT;
CREATE DCM PROJECT DCM_LEARNING.TEST.DCM_PROJECT_PROD_SIM;

CREATE DCM PROJECT DCM_LEARNING.PROJECTS.DCM_PROJECT_DEMO;
CREATE DCM PROJECT DCM_LEARNING.PROJECTS.DCM_PROJECT_DEMO_PROD;