SHOW WORKSPACES IN ACCOUNT;
CREATE or replace DBT PROJECT DCM_LEARNING.PROJECTS.SNOWFLAKE_PROJECT
  FROM 'snow://workspace/DCM_LEARNING.PROJECTS."Shared Workspace"/versions/live/DCM_DEMO_PROJECT/sources/dbt/snowflake_project'
  DEFAULT_TARGET = 'dev';
  SHOW DBT PROJECTS IN ACCOUNT;

  EXECUTE DBT PROJECT DCM_LEARNING.PROJECTS.SNOWFLAKE_PROJECT
    ARGS = 'run --target dev';
GRANT ROLE DBT_DEV_ROLE TO ROLE ACCOUNTADMIN;



CREATE OR ALTER TASK DCM_LEARNING.PROJECTS.run_sequential_dbt
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
    EXECUTE DBT PROJECT DCM_LEARNING.PROJECTS.SNOWFLAKE_PROJECT
        ARGS = 'run --target dev';

EXECUTE TASK DCM_LEARNING.PROJECTS.run_sequential_dbt;



SELECT NAME, STATE, ERROR_MESSAGE, COMPLETED_TIME
FROM TABLE(DCM_LEARNING.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'RUN_SEQUENTIAL_DBT'))
ORDER BY SCHEDULED_TIME DESC LIMIT 1;