--Define a sufficient dev role to access database,schema,warehouse,table
DEFINE ROLE dbt_dev_role
    COMMENT = 'Least-privilege role for dbt DEV runs';
GRANT CREATE TABLE ON SCHEMA DCM_LEARNING.TEST TO ROLE dbt_dev_role;
GRANT USAGE ON DATABASE DCM_LEARNING TO ROLE dbt_dev_role;
GRANT USAGE ON SCHEMA DCM_LEARNING.TEST TO ROLE dbt_dev_role;
GRANT SELECT, INSERT ON TABLE DCM_LEARNING.TEST.ORDERS_RAW TO ROLE dbt_dev_role;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dbt_dev_role;
GRANT CREATE VIEW ON SCHEMA DCM_LEARNING.TEST TO ROLE dbt_dev_role;